objects=\
mvs10_error_handler.o\
mvs_add_disparity_map.o\
mvs_add_imagepoint_to_threedpoint.o\
mvs_add_match.o\
mvs_check_threedpoints.o\
mvs_compute_disparity_map.o\
mvs_compute_reprojection_error.o\
mvs_compute_t_from_R_C.o\
mvs_get_camera_pair_stats_from_match_file.o\
mvs_get_camera_pair_stats_from_sfm.o\
mvs_get_sfm_camera_ind.o\
mvs_get_threedpoints_nbr.o\
mvs_init_pixel_to_threedpoint_arr.o\
mvs_lbfgs_bundle_adjustment.o\
mvs_merge_threedpoints.o\
mvs_pba_bundle_adjustment.o\
mvs_read_nvm.o\
mvs_rectify_image_pair.o\
mvs_remove_spurious_imagepoints.o\
mvs_remove_spurious_threedpoints.o\
mvs_swap_matches.o
